config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  resources :events

  resources :home, only: [:index, :create]

  get '/about', to: 'home#about'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	validates :title, :details, :eventdate, :applicationstart, :applicationend, :requirement, :link, :image, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.00}

	validate :application_period_error, :eventdate_error

	def application_period_error
		if applicationend < applicationstart
			errors.add(:applicationend, "Cannot have application end before the application start!")
		end
	end

	def eventdate_error
		if applicationend > eventdate
			errors.add(:eventdate, "You can't have an event when the application is not yet over")
		end
	end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    # @search = Event.search do
    #   fulltext params[:search]
    # end
    @events = Event.all.order("eventdate ASC")
    # @events = @search.results
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :details, :eventdate, :applicationstart, :applicationend, :requirement, :link, :price, :image, :company)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
  	@subscription = Subscription.new
  end

  def about

  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to home_index_path, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: home_index_path }
      else
        format.html { redirect_to home_index_path, alert: 'Subscription was unsuccessful.' }
        format.json { render :show, status: :created, location: home_index_path }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :details %>
        <%= f.text_area :details, class: "form-control", rows: 4 %>
      </div>

      <div class="field">
        <%= f.label :requirement %>
        <%= f.text_area :requirement, class: "form-control", rows: 4 %>
      </div>

      <div class="field">
        <%= f.label :eventdate %>
        <%= f.text_field :eventdate, class: "form-control", type: "datetime-local" %>
      </div>

      <div class="field">
        <%= f.label :applicationstart %>
        <%= f.text_field :applicationstart, class: "form-control", type: "datetime-local" %>
      </div>

      <div class="field">
        <%= f.label :applicationend %>
        <%= f.text_field :applicationend, class: "form-control", type: "datetime-local" %>
      </div>

      <div class="field">
        <%= f.label :link %>
        <%= f.text_field :link, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :image %>
        <%= f.text_field :image, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :company%>
        <%= f.text_field :company, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
</div>



<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% @events.in_groups_of(3, false).each do |group| %>
<div class="row">

  <% group.each do |event| %>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="events/<%=event.id %>">
          <%= image_tag(event.image, size: "200x100", style: "width: 100%") %>
          <div class="caption">
            <h3><%= event.title %></h3>

            <% if event.price == 0 %>
              <span class="label label-success">Free!</span>
            <% else %>
              <span class="label label-primary"><%= number_to_currency(event.price, unit: "₱") %></span>
            <% end %>

            <p><%= simple_format truncate(event.details, length: 140) %></p>
          </div>
        </a>
      </div>
    </div>
  <% end %>
  <!--<%= link_to 'New Event', new_event_path %>-->

</div>
<% end %>



<!-- <p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.details %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
 -->

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-1">

        <div class="thumbnail">
          <%= image_tag(@event.image, class: "img-responsive") %>
        </div>
        <!-- <div class="page-header">
          <h1><%= @event.title %></h1>
        </div> -->
      </div>

      <div class="col-md-3">
        <!-- <div class="panel panel-default"> -->
        
        <h3><%= @event.eventdate.strftime("%B") %></h3>
        <h4 class="text-muted"><%= @event.eventdate.strftime("%d") %></h4>
      
        <h2><%= @event.title %></h2>
        <h4 class="text-muted">by <%= @event.company %></h4>
      
        <hr>
        <% if @event.price == 0 %>
          <h2>Free!</h2>
        <% else %>
          <h2><%= number_to_currency(@event.price, unit: "₱") %></h2>
        <% end %>
        
        <!-- </div> -->
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-1">
    <h4><b>Description</b></h4>
      <%= simple_format @event.details %>
    <br>
    <h4><b>Website:</b> <%= link_to @event.link, @event.link %></h4>

    <br>
    <h4><b>Requirements to join</b></h4>
    <%= simple_format @event.requirement %>
    



    </div>

    <div class="col-md-3">
      <h3><b>Application Period</b></h3>
      From <%= @event.applicationstart.strftime("%B %d") %> - To <%= @event.applicationend.strftime("%B %d, %Y") %>
    </div>

  </div>
</div>


<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @event.image %>
</p>

<p>
  <strong>Details:</strong>
  <%= @event.details.html_safe %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @event.requirement %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.eventdate %>
</p>

<p>
  <strong>Application period:</strong>
  From: <%= @event.applicationstart %> - To: <%= @event.applicationend %>
</p>

<p>
  <strong>To see more, view this link:</strong>
  <%= @event.link %>
</p>

<p>
  <strong>Price:</strong>
  <% if @event.price == 0 %>
  	Free!
  <% else %>
  <%= @event.price %>
  <% end %>
</p

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
 -->

app/views/home/about.html.erb
<h3>
  About us
</h3>
<div class="row">
    <div class="col-md-4">
      <p>
        We connect undergraduate students to opportunities to enhance their careers by curating events, competitions, and other opportunities that are value adding for them.
      </p>
    </div>

    <div class="col-md-4">
      <p>
        We were once a group of students who loved attending career-building events such as competitions and workshops. Finding events was hard - we would scour the web for opportunities only to come up blank. All the ones we attended were just from word of mouth.
      </p>
    </div>
    <div class="col-md-4">
      <p>
        To solve this problem and make college career events easier to find, we built College Plus. College Plus curates all the college events you can think of on one webpage so that you can have the resources you need to maximize your college experience.
      </p>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag("caro1.png",height: "50") %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag("caro2.png",height: "50") %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag("caro3.png",height: "50")%>
          <div class="carousel-caption">
          </div>
        </div>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div> <!-- Carousel -->
  </div>
  <div class="col-md-6">
    <blockquote>
      <p>
        Linking ambitious students to career-enhancing events
      </p>
      <i>
        Keith Lim
      </i>
    </blockquote>
    <blockquote>
      <p>
        Giving You the Plus Factor
      </p>
      <i>
        Cedrick Rances
      </i>
    </blockquote>
    <h3><p>Subscribe</p></h3>
    <!-- <form action="/home" method="post" accept-charset="UTF-8">
      <input type="text" name="email" placeholder="What's your email?" />
      <input type="submit" class="btn btn-primary" value="Subscribe" />
    </form>
 -->
    <%= render "subscriptions/form" %>

    Like us on Facebook
    <div class="fb-like" data-href="https://www.facebook.com/CollegePlus/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>
  </div>
</div>



<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=259724744473517";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '259724744473517',
            xfbml      : true,
            version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collegeplus</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="container" style="width: 90%">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/events"><img src="https://scontent.fcrk1-1.fna.fbcdn.net/v/t35.0-12/16833636_1312030608840079_168339245_o.png?oh=ee1050f99aef2491d7650ff5037ad9de&oe=58AB2517" style="max-width:120px; margin-top: -15px;"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="/home">Home</a></li>
            <li>
              <a href="/events">Events</a></li>

            <li>
              <a href="/about">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>

    <% if notice.present? %>
      <br>
      <div class="container">
        <div class="alert alert-info"><%= notice %></div>
      </div>
    <% elsif alert.present? %>
      <br>
      <div class="container">
        <div class="alert alert-danger"><%= alert %></div>
      </div>
    <% end %>

    <%= yield %>

  </div>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<div class="row">

  <%= form_for(@subscription) do |f| %>

    <div class="col-md-9 input-group">
      <%= f.text_field :email, class: "form-control", type: "email", placeholder: "What's your email?" %>

      <span class="input-group-btn">
        <%= f.submit nil, class: "btn btn-success" %>
      </span>

    </div>



  <% end %>
  </div>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>